import json
from pathlib import Path

from django.apps import apps
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import connection
from django.db.utils import OperationalError, ProgrammingError


# These records are deliberately excluded from sqlite_data.json by the export
# script. They are environment-specific or regenerated by Django migrations,
# so they must not participate in the source/target data-count comparison.
IGNORED_MODEL_LABELS = {
    "admin.logentry",
    "auth.permission",
    "contenttypes.contenttype",
    "sessions.session",
}


class Command(BaseCommand):
    help = (
        "Create a record-count inventory for transferable managed models and "
        "optionally compare it with a previous inventory file."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            type=Path,
            help="Write the current inventory to this JSON file.",
        )
        parser.add_argument(
            "--compare",
            type=Path,
            help="Compare current model counts with a previous inventory JSON file.",
        )

    def handle(self, *args, **options):
        inventory = self._build_inventory()
        output_path = options.get("output")
        compare_path = options.get("compare")

        if output_path:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(
                json.dumps(inventory, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            self.stdout.write(self.style.SUCCESS(f"Inventory saved to {output_path}"))

        if compare_path:
            self._compare(inventory, compare_path)
        elif not output_path:
            self.stdout.write(json.dumps(inventory, ensure_ascii=False, indent=2))

    def _build_inventory(self):
        model_counts = {}
        skipped_models = {}

        for model in sorted(apps.get_models(), key=lambda item: item._meta.label_lower):
            if model._meta.proxy or not model._meta.managed:
                continue

            label = model._meta.label_lower
            if label in IGNORED_MODEL_LABELS:
                continue

            try:
                model_counts[label] = model._default_manager.count()
            except (OperationalError, ProgrammingError) as exc:
                skipped_models[label] = str(exc)

        return {
            "database": {
                "vendor": connection.vendor,
                "name": str(settings.DATABASES["default"]["NAME"]),
            },
            "models": model_counts,
            "skipped_models": skipped_models,
            "ignored_models": sorted(IGNORED_MODEL_LABELS),
        }

    def _compare(self, current, compare_path: Path):
        if not compare_path.is_file():
            raise CommandError(f"Comparison inventory not found: {compare_path}")

        try:
            previous = json.loads(compare_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise CommandError(f"Cannot read comparison inventory: {exc}") from exc

        previous_models = {
            label: count
            for label, count in previous.get("models", {}).items()
            if label not in IGNORED_MODEL_LABELS
        }
        current_models = {
            label: count
            for label, count in current.get("models", {}).items()
            if label not in IGNORED_MODEL_LABELS
        }
        labels = sorted(set(previous_models) | set(current_models))
        mismatches = []

        for label in labels:
            before = previous_models.get(label)
            after = current_models.get(label)
            if before != after:
                mismatches.append((label, before, after))

        if current.get("skipped_models"):
            for label, error in current["skipped_models"].items():
                mismatches.append((label, "counted previously", f"skipped: {error}"))

        if mismatches:
            self.stderr.write(self.style.ERROR("Database inventory mismatch:"))
            for label, before, after in mismatches:
                self.stderr.write(f"- {label}: before={before}, after={after}")
            raise CommandError(
                f"Inventory comparison failed with {len(mismatches)} mismatch(es)."
            )

        self.stdout.write(
            self.style.SUCCESS(
                f"Inventory comparison passed for {len(labels)} transferable managed model(s)."
            )
        )
