# Generated by Django 4.2.7 on 2026-01-11 19:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budgeted_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "budgeted_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "budgeted_total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "actual_unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "actual_total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "quantity_variance",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "price_variance",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "total_variance",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=7
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_budget", "On Budget"),
                            ("over_budget", "Over Budget"),
                            ("under_budget", "Under Budget"),
                        ],
                        default="on_budget",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "boq_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_budgets",
                        to="procurement.billofquantities",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_budgets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_budgets",
                        to="procurement.itemmaster",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_budgets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["item__full_code"],
            },
        ),
        migrations.CreateModel(
            name="CostForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField(auto_now_add=True)),
                (
                    "forecast_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "forecast_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "forecast_total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "quantity_variance",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "price_variance",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "total_variance",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low (50–70%)"),
                            ("medium", "Medium (70–85%)"),
                            ("high", "High (85–95%)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="cost_control.budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_forecasts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_forecasts",
                        to="procurement.itemmaster",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_forecasts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_date"],
            },
        ),
        migrations.CreateModel(
            name="CostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField(auto_now_add=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_budgeted",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "total_actual",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "total_variance",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=15
                    ),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=7
                    ),
                ),
                ("on_budget_count", models.IntegerField(default=0, editable=False)),
                ("over_budget_count", models.IntegerField(default=0, editable=False)),
                ("under_budget_count", models.IntegerField(default=0, editable=False)),
                ("recommendations", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
                "unique_together": {("project", "report_type", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="BudgetAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("overrun", "Budget Overrun"),
                            ("threshold", "Threshold Exceeded"),
                            ("variance", "High Variance"),
                            ("forecast", "Forecast Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="cost_control.budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_alerts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_alerts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["project", "severity"],
                        name="cost_contro_project_fc32ac_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_resolved"],
                        name="cost_contro_is_acti_835525_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["project", "status"], name="cost_contro_project_af3b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["item"], name="cost_contro_item_id_837f2a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("project", "item")},
        ),
    ]
