# Generated by Django 5.2.17 on 2026-09-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_control', '0001_initial'),
        ('reports', '0019_boq_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='boq_item',
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='sub_item',
            field=models.ForeignKey(blank=True, help_text='The project BOQ item this alert is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_alerts', to='reports.projectphasesubitem'),
        ),
        migrations.AlterField(
            model_name='budgetalert',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cost_control.budget'),
        ),
    ]
