# Generated by Django 4.2.7 on 2026-01-11 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "project_symbol",
                    models.CharField(
                        help_text="Unique project symbol/code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        help_text="Contract number", max_length=100, unique=True
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        help_text="Client or CMC name (e.g., One Stop)", max_length=255
                    ),
                ),
                ("start_date", models.DateField(help_text="Project start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive Maintenance"),
                            ("corrective", "Corrective Maintenance"),
                            ("predictive", "Predictive Maintenance"),
                            ("routine", "Routine Maintenance"),
                        ],
                        default="preventive",
                        help_text="Type of maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Project status",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Project location", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="Project manager",
                        limit_choices_to={"role": "project_manager"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floor_number",
                    models.CharField(
                        help_text="Floor name or number (e.g., G, 1, 2, B1)",
                        max_length=50,
                    ),
                ),
                (
                    "floor_name",
                    models.CharField(
                        blank=True,
                        help_text="Floor name or description",
                        max_length=255,
                    ),
                ),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Floor area in square meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Floor description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Floor",
                "verbose_name_plural": "Project Floors",
                "ordering": ["project", "floor_number"],
                "unique_together": {("project", "floor_number")},
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_symbol"], name="projects_pr_project_11fcf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["contract_number"], name="projects_pr_contrac_c28748_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
    ]
