# Generated by Django 5.2.4 on 2026-09-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contract_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total contract value, used to convert phase progress percentages into monetary amounts for financial reports",
                max_digits=15,
                null=True,
            ),
        ),
    ]
