# Generated by Django 5.2.17 on 2026-09-06 12:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_contract_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_payment_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Advance/mobilization payment value, recovered against progress payments over the life of the contract', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='performance_retention_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='% of each certified payment withheld as performance retention (e.g. 10.00 for 10%)', max_digits=5),
        ),
    ]
