# Generated by Django 5.2.17 on 2026-09-07 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_advance_payment_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_engineer',
            field=models.ForeignKey(blank=True, help_text='Site engineer assigned to this project -- the only one who may create its Daily reports', limit_choices_to={'role': 'site_engineer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineered_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(help_text='Project manager -- creates the Monthly (EDGE) and Owner Financial reports', limit_choices_to={'role': 'project_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
