# Generated by Django 5.2.17 on 2026-09-20 09:18

import django.db.models.deletion
import projects.models
import projects.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_site_engineer_alter_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('car', "Contractor's All Risks (CAR)"), ('third_party', 'Third-party liability'), ('workers', "Workers' compensation / employer's liability"), ('performance_bond', 'Performance bond'), ('advance_payment', 'Advance payment guarantee'), ('other', 'Other')], max_length=30)),
                ('insurer', models.CharField(help_text='Insurance company / issuing bank', max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('insured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('document', models.FileField(upload_to=projects.models.insurance_upload_path, validators=[projects.validators.validate_document_file])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('contract', 'Contract / agreement'), ('conditions', 'Conditions of contract'), ('specifications', 'Specifications'), ('boq', 'Bill of quantities'), ('addendum', 'Addendum / clarification'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=projects.models.tender_upload_path, validators=[projects.validators.validate_document_file])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('insurance', 'Insurance'), ('tender', 'Tender documents'), ('drawings', 'Start work from approved drawings')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Blank for stages marked complete automatically on projects that were already running', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_project_stages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'key')},
            },
        ),
    ]
