# Generated by Django 5.2.17 on 2026-09-23 09:49

import django.db.models.deletion
import projects.models
import projects.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_backfill_project_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='key',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('tender', 'Tender documents'), ('drawings', 'Drawings approved for construction'), ('schedule', 'Project schedule'), ('plans', 'Project management plans')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectManagementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('eshs', 'Environmental, Social, Health & Safety (ESHS) Management Plan'), ('quality', 'Quality Management Plan'), ('risk', 'Risk Management Plan'), ('technical_approach', 'Technical Approach and Methodology'), ('project_team', 'Project Team: Organization, Staffing'), ('code_of_conduct', 'Code of Conduct'), ('site_management', 'Site Management and Logistics')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to=projects.models.management_plan_upload_path, validators=[projects.validators.validate_document_file])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_mobilization_demobilization', models.BooleanField(default=False, verbose_name='1. Mobilization and Demobilization')),
                ('checklist_access_control', models.BooleanField(default=False, verbose_name='2. Access Control')),
                ('checklist_sign_boards', models.BooleanField(default=False, verbose_name='3. Sign Boards')),
                ('checklist_security_provisions', models.BooleanField(default=False, verbose_name='4. Security Provisions and Access Control')),
                ('checklist_demobilization', models.BooleanField(default=False, verbose_name='5. Demobilization')),
                ('checklist_traffic_public_safety', models.BooleanField(default=False, verbose_name='6. Maintenance of Traffic and Public Safety')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_plans', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRegulatoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(choices=[('government', 'Government'), ('municipality', 'Municipality'), ('civil_defense', 'Civil Defense')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to=projects.models.regulatory_upload_path, validators=[projects.validators.validate_document_file])),
                ('approval_number', models.CharField(blank=True, max_length=100)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_approvals', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['body', '-uploaded_at'],
            },
        ),
    ]
