# Generated by Django 5.2.17 on 2026-09-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_specificationsection_content'),
        ('projects', '0007_alter_projectstage_key_projectmanagementplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicable_spec_sections',
            field=models.ManyToManyField(blank=True, help_text='Which sections of the company standard (One Stop Standards and Specifications) apply to this project, based on its own nature (e.g. no subcontractors -> that section stays off).', related_name='projects', to='core.specificationsection'),
        ),
    ]
