# Generated by Django 4.2.7 on 2026-01-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("report_submitted", "Report Submitted"),
                            ("report_approved", "Report Approved"),
                            ("report_rejected", "Report Rejected"),
                            ("user_created", "User Created"),
                            ("password_reset", "Password Reset"),
                        ],
                        help_text="Template type",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject", max_length=255),
                ),
                ("body", models.TextField(help_text="Email body (supports HTML)")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the template is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Setting key", max_length=100, unique=True
                    ),
                ),
                ("value", models.TextField(help_text="Setting value")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the setting"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
