# Generated by Django 5.2.17 on 2026-09-23 10:34

import core.models
import django.db.models.deletion
import projects.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Volume I"', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('revision', models.CharField(blank=True, help_text='e.g. "REV03", "Final July 6, 2026"', max_length=100)),
                ('document', models.FileField(upload_to=core.models.specification_upload_path, validators=[projects.validators.validate_document_file])),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specification Volume',
                'verbose_name_plural': 'Specification Volumes',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. "01010"', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.specificationvolume')),
            ],
            options={
                'verbose_name': 'Specification Section',
                'verbose_name_plural': 'Specification Sections',
                'ordering': ['order', 'code'],
            },
        ),
    ]
