# Generated by Django 5.2.17 on 2026-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_specificationvolume_specificationsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsection',
            name='content',
            field=models.TextField(blank=True, help_text="This section's own text, extracted from the volume document, for the popup card and its standalone PDF"),
        ),
    ]
