# Generated by Django 5.2.17 on 2026-10-10 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0011_remove_purchaserequisitionline_boq_item_and_more'),
        ('projects', '0008_project_applicable_spec_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Printed on the tool label, e.g. EQ-0001 (assigned automatically)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Tool name', max_length=150)),
                ('category', models.CharField(blank=True, help_text='e.g. Grinder, Drill, Ladder, Vibrator', max_length=60)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_no', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('working', 'Working'), ('needs_maintenance', 'Needs maintenance'), ('in_maintenance', 'In maintenance'), ('broken', 'Broken'), ('scrapped', 'Scrapped')], default='working', max_length=20)),
                ('holder', models.CharField(blank=True, help_text='Person who has the tool on site', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/tools/')),
                ('notes', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, db_index=True, editable=False, help_text='Where the record was imported from (makes the import safe to repeat)', max_length=40)),
                ('last_inventory_date', models.DateField(blank=True, help_text='Last time the tool was seen in a stock-take', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='projects.project')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='procurement.warehouse')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ToolMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('scrapped', 'Scrapped'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('problem', models.TextField(help_text='What is wrong / what service is needed (e.g. needs a new motor and carbon brushes)')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, help_text='Workshop / supplier doing the repair', max_length=150)),
                ('parts', models.CharField(blank=True, max_length=300)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('result_note', models.CharField(blank=True, max_length=300)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to='equipment.tool')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening', 'Received'), ('issue', 'Issued to project'), ('return', 'Returned'), ('transfer', 'Transferred')], default='transfer', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=10)),
                ('holder', models.CharField(blank=True, help_text='Person receiving the tool on site', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('return_condition', models.CharField(blank=True, choices=[('ok', 'Good'), ('needs_maintenance', 'Needs maintenance'), ('scrap', 'Scrap')], max_length=20)),
                ('return_note', models.CharField(blank=True, max_length=300)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.project')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.warehouse')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.project')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.warehouse')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='equipment.tool')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
    ]
