# Generated by Django 5.2.17 on 2026-09-23 12:32

import django.core.validators
import django.db.models.deletion
import projects.validators
import subcontractors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0011_remove_purchaserequisitionline_boq_item_and_more'),
        ('projects', '0008_project_applicable_spec_sections'),
        ('reports', '0020_scheduletask_activity_id_scheduletask_actual_finish_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('scope_description', models.TextField(help_text='What this subcontractor is engaged to execute')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('signed_document', models.FileField(blank=True, help_text='The signed agreement document', null=True, upload_to=subcontractors.models.agreement_document_path, validators=[projects.validators.validate_document_file])),
                ('total_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_agreements_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_agreements', to='projects.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor_agreements', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorAgreementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="Defaults to the BOQ item's own name if left blank", max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='subcontractors.subcontractoragreement')),
                ('sub_item', models.ForeignKey(help_text='The project BOQ item this scope of work is charged to', on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor_agreement_lines', to='reports.projectphasesubitem')),
            ],
            options={
                'ordering': ['agreement', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorAgreementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subcontractors.subcontractoragreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_agreement_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='subcontractoragreement',
            index=models.Index(fields=['project', 'status'], name='subcontract_project_2a8336_idx'),
        ),
        migrations.AddIndex(
            model_name='subcontractoragreement',
            index=models.Index(fields=['vendor'], name='subcontract_vendor__842da7_idx'),
        ),
    ]
