# Generated by Django 5.2.17 on 2026-09-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

GENERAL_TERMS = """\
1. تخضع كل اتفاقية مصانعة (Musana'a) لأحكام العقد الرئيسي للمشروع، وتُقرأ معه كوثيقة واحدة؛ لا يجوز لأي شرط في هذه الاتفاقية أن يتعارض مع العقد الرئيسي.
2. يلتزم المقاول المصانع بتنفيذ الأعمال طبقاً للمخططات المعتمدة، ومواصفات الشركة (One Stop Standards and Specifications)، وجدول المشروع الزمني المعتمد.
3. يوفر المقاول المصانع العمالة والأدوات اللازمة لتنفيذ نطاق العمل المحدد في بنود الاتفاقية، ما لم يُنص صراحة على خلاف ذلك.
4. تُصرف الدفعات على أساس نسبة الإنجاز الفعلي المُقاس والمعتمد من مهندس الموقع، وليس على أساس مبالغ مقطوعة دون قياس.
5. تخضع جميع الأعمال والمواد لفحص ومراجعة الجودة (QA/QC) من الشركة قبل اعتمادها ضمن أي مستخلص.

1. Each Musana'a agreement is governed by, and read together with, the project's main contract; no clause here may conflict with it.
2. The subcontractor shall execute the works strictly per the approved drawings, the company's own Standards and Specifications, and the approved project schedule.
3. The subcontractor supplies its own labor and tools for the scope of work priced in this agreement's lines, unless expressly stated otherwise.
4. Payments are certified against actually measured and approved progress, never as lump sums without measurement.
5. All work and materials are subject to the company's QA/QC inspection and approval before being included in any certified payment.
"""

PENALTY_CLAUSES = """\
1. في حال التأخر عن الجدول الزمني المعتمد لأسباب تعود للمقاول المصانع، تُطبّق غرامة تأخير قدرها 0.5% من قيمة الأعمال غير المنفذة عن كل يوم تأخير، وبحد أقصى 10% من القيمة الإجمالية للاتفاقية.
2. تُعاد الأعمال المرفوضة (Rejected/NCR) على نفقة ووقت المقاول المصانع، دون أي تمديد للجدول الزمني أو تعويض إضافي.
3. عند عدم معالجة الملاحظات خلال المهلة المحددة بإشعار كتابي، يحق للشركة تكليف طرف ثالث لإنجاز الأعمال وخصم كامل التكلفة من مستحقات المقاول المصانع.
4. يحق للشركة حجز نسبة ضمان (Retention) من كل دفعة حتى تسليم الأعمال واعتمادها نهائياً.

1. Delay attributable to the subcontractor incurs liquidated damages of 0.5% of the value of unexecuted work per day of delay, capped at 10% of the agreement's total value.
2. Rejected work / NCRs are reworked at the subcontractor's own cost and time, with no schedule extension or additional compensation.
3. If a defect is not remedied within the notice period, the company may engage a third party to complete it and deduct the full cost from the subcontractor's dues.
4. The company may withhold a retention percentage from each payment until the work is finally handed over and approved.
"""

CODE_OF_CONDUCT = """\
1. يلتزم المقاول المصانع وعماله بعدم ممارسة أي شكل من أشكال التمييز أو التحرش أو عمالة الأطفال أو العمل القسري.
2. يُمنع منعاً باتاً تقديم أو قبول أي رشوة أو عمولة أو هدية قد تشكل تضارب مصالح مع موظفي الشركة.
3. يحافظ المقاول المصانع على سرية معلومات المشروع ولا يفصح عنها لأي طرف ثالث دون إذن كتابي مسبق.
4. يلتزم عمال المقاول المصانع باحترام العادات والتقاليد المحلية وأوقات العمل النظامية بالموقع.

1. The subcontractor and its workers shall not engage in any form of discrimination, harassment, child labor, or forced labor.
2. Offering or accepting any bribe, kickback, or gift that could create a conflict of interest with company staff is strictly prohibited.
3. The subcontractor shall keep project information confidential and shall not disclose it to any third party without prior written consent.
4. The subcontractor's workers shall respect local customs and the site's official working hours.
"""

SAFETY_COMMITMENT = """\
1. يلتزم المقاول المصانع الالتزام الكامل بخطة السلامة (HSE) الخاصة بالشركة وإجراءات "إدارة الموقع واللوجستيات" المعتمدة.
2. يلتزم جميع العمال بارتداء معدات الحماية الشخصية (PPE) والحضور الإلزامي لجلسات التوعية اليومية (Toolbox Talk).
3. يجب الإبلاغ الفوري عن أي حادث أو شبه حادث لمهندس الموقع دون تأخير.
4. يحق لمهندس الموقع إيقاف أي عمل غير آمن فوراً ودون أي مسؤولية على الشركة عن التوقف الناتج.
5. تُعتبر المخالفات المتكررة لتعليمات السلامة سبباً كافياً لإنهاء الاتفاقية دون إشعار مسبق.

1. The subcontractor shall fully comply with the company's HSE plan and its approved Site Management and Logistics procedures.
2. All workers must wear the required PPE and attend the mandatory daily toolbox talks.
3. Any incident or near-miss must be reported to the site engineer immediately, without delay.
4. The site engineer may stop any unsafe work immediately, with no liability to the company for the resulting stoppage.
5. Repeated safety violations are sufficient grounds to terminate the agreement without prior notice.
"""


def seed_demo_general_terms(apps, schema_editor):
    # Windows checkouts can hand these triple-quoted strings to us with \r\n line endings; normalize so
    # code that splits on a literal blank line ("\n\n") -- e.g. subcontractors/pdf.py's bilingual layout --
    # reliably finds it.
    SubcontractorGeneralTerms = apps.get_model('subcontractors', 'SubcontractorGeneralTerms')
    SubcontractorGeneralTerms.objects.get_or_create(pk=1, defaults={
        'general_terms': GENERAL_TERMS.replace('\r\n', '\n'),
        'penalty_clauses': PENALTY_CLAUSES.replace('\r\n', '\n'),
        'code_of_conduct': CODE_OF_CONDUCT.replace('\r\n', '\n'),
        'safety_commitment': SAFETY_COMMITMENT.replace('\r\n', '\n'),
    })


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorGeneralTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_terms', models.TextField(blank=True, help_text="General contract terms and conditions applicable to all subcontract (Musana'a) works")),
                ('penalty_clauses', models.TextField(blank=True, help_text='Liquidated damages / penalty clauses for delay, defects and rework')),
                ('code_of_conduct', models.TextField(blank=True, help_text='Ethical / code-of-conduct commitments required of the subcontractor')),
                ('safety_commitment', models.TextField(blank=True, help_text='General (HSE) safety commitment required of the subcontractor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcontractor General Terms & Conditions',
                'verbose_name_plural': 'Subcontractor General Terms & Conditions',
            },
        ),
        migrations.RunPython(seed_demo_general_terms, migrations.RunPython.noop),
    ]
