# Generated by Django 5.2.17 on 2026-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractors', '0002_subcontractorgeneralterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractoragreement',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic / عربي'), ('en', 'English')], default='ar', help_text='Chosen once when the agreement is created -- its printed PDF is single-language, laid out right-to-left for Arabic, rather than mixing both languages on the page.', max_length=2),
        ),
    ]
