# Generated by Django 5.2.17 on 2026-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('general_manager', 'General Manager'), ('engineering_manager', 'Engineering Manager'), ('project_manager', 'Project Manager'), ('site_engineer', 'Site Engineer')], default='site_engineer', help_text='User role in the system', max_length=20),
        ),
    ]
