# Generated by Django 5.2.17 on 2026-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_report_section_order',
            field=models.JSONField(blank=True, help_text="This user's own preferred order for the Daily Report page's section list (saved via its move-up/move-down controls on each section); unset falls back to the page's default order", null=True),
        ),
    ]
