# Generated by Django 5.2.17 on 2026-10-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_daily_report_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('general_manager', 'General Manager'), ('engineering_manager', 'Engineering Manager'), ('project_manager', 'Project Manager'), ('site_engineer', 'Site Engineer'), ('procurement_officer', 'Procurement Officer'), ('accountant', 'Accountant')], default='site_engineer', help_text='User role in the system', max_length=20),
        ),
    ]
