# Generated by Django 4.2.7 on 2026-01-11 19:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        help_text="Auto-generated unique report number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date when report was created"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Current status of the report",
                        max_length=20,
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, help_text="When the report was approved", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "weather_conditions",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("rainy", "Rainy"),
                            ("cloudy", "Cloudy"),
                            ("windy", "Windy"),
                            ("mixed", "Mixed"),
                            ("stormy", "Stormy"),
                        ],
                        help_text="Weather conditions during the day",
                        max_length=50,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks and notes", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project manager who approved the report",
                        limit_choices_to={"role": "project_manager"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated construction project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "site_engineer",
                    models.ForeignKey(
                        help_text="Site engineer who created the report",
                        limit_choices_to={"role": "site_engineer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Report",
                "verbose_name_plural": "Daily Reports",
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        help_text="Auto-generated unique report number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date when report was created"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Current status of the report",
                        max_length=20,
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, help_text="When the report was approved", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "reporting_period_from",
                    models.DateField(help_text="Start date of the reporting period"),
                ),
                (
                    "reporting_period_to",
                    models.DateField(help_text="End date of the reporting period"),
                ),
                (
                    "weather_conditions",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("rainy", "Rainy"),
                            ("cloudy", "Cloudy"),
                            ("windy", "Windy"),
                            ("mixed", "Mixed"),
                        ],
                        help_text="Weather conditions during the period",
                        max_length=50,
                    ),
                ),
                (
                    "general_description",
                    models.TextField(
                        blank=True,
                        help_text="General description of activities",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project manager who approved the report",
                        limit_choices_to={"role": "project_manager"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated construction project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "site_engineer",
                    models.ForeignKey(
                        help_text="Site engineer who created the report",
                        limit_choices_to={"role": "site_engineer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Report",
                "verbose_name_plural": "Monthly Reports",
                "ordering": ["-reporting_period_to", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=150)),
                ("total_hours", models.DecimalField(decimal_places=1, max_digits=6)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="reports.monthlyreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("completion_percentage", models.PositiveIntegerField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="reports.monthlyreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_description",
                    models.CharField(
                        help_text="Description of the material", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of material",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(help_text="Unit of measurement", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Monthly report this material belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_supplies",
                        to="reports.monthlyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Supply",
                "verbose_name_plural": "Material Supplies",
                "ordering": ["report", "material_description"],
            },
        ),
        migrations.CreateModel(
            name="FloorActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_description",
                    models.TextField(
                        help_text="Description of activities on this floor"
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of completion",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        help_text="Floor where activity occurred",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projectfloor",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Monthly report this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_activities",
                        to="reports.monthlyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor Activity",
                "verbose_name_plural": "Floor Activities",
                "ordering": ["report", "floor"],
            },
        ),
        migrations.CreateModel(
            name="ExternalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_description",
                    models.TextField(help_text="Description of external work"),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of completion",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Monthly report this work belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_works",
                        to="reports.monthlyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Work",
                "verbose_name_plural": "External Works",
                "ordering": ["report"],
            },
        ),
        migrations.CreateModel(
            name="DailyWorkForce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("management", "Management"),
                            ("skilled", "Skilled Labor"),
                            ("unskilled", "Unskilled Labor"),
                            ("contractor", "Contractor"),
                        ],
                        help_text="Category of workforce",
                        max_length=20,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Job designation or title", max_length=255
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        help_text="Number of workers in this category",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Daily report this workforce belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workforce",
                        to="reports.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Work Force",
                "verbose_name_plural": "Daily Work Forces",
                "ordering": ["report", "category"],
            },
        ),
        migrations.CreateModel(
            name="DailyVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_time", models.TimeField(help_text="Time of visit")),
                (
                    "visitor_name",
                    models.CharField(help_text="Name of the visitor", max_length=255),
                ),
                (
                    "representing",
                    models.CharField(
                        blank=True,
                        help_text="Organization or company the visitor represents",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Daily report this visitor belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="reports.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Visitor",
                "verbose_name_plural": "Daily Visitors",
                "ordering": ["report", "visit_time"],
            },
        ),
        migrations.CreateModel(
            name="DailyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_description",
                    models.CharField(
                        help_text="Description of the material", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of material",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (cubic meters, tons, pieces, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Daily report this material belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_materials",
                        to="reports.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Material",
                "verbose_name_plural": "Daily Materials",
                "ordering": ["report", "material_description"],
            },
        ),
        migrations.CreateModel(
            name="DailyEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(help_text="Name of the equipment", max_length=255),
                ),
                (
                    "hours_worked",
                    models.IntegerField(
                        help_text="Number of hours equipment worked",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "quantity_idle",
                    models.IntegerField(
                        default=0,
                        help_text="Quantity of equipment idle",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Daily report this equipment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="reports.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Equipment",
                "verbose_name_plural": "Daily Equipment",
                "ordering": ["report", "equipment_name"],
            },
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("excavation", "Excavation"),
                            ("foundation", "Foundation Work"),
                            ("structure", "Structural Work"),
                            ("finishing", "Finishing Work"),
                            ("painting", "Painting"),
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("hvac", "HVAC"),
                            ("inspection", "Inspection"),
                            ("testing", "Testing"),
                            ("other", "Other"),
                        ],
                        help_text="Type of activity",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location of activity on site",
                        max_length=255,
                    ),
                ),
                (
                    "activity_description",
                    models.TextField(help_text="Detailed description of the activity"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Daily report this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to="reports.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Activity",
                "verbose_name_plural": "Daily Activities",
                "ordering": ["report", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UpcomingWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_description",
                    models.TextField(help_text="Description of upcoming work"),
                ),
                (
                    "planned_start_date",
                    models.DateField(help_text="Planned start date for this work"),
                ),
                (
                    "planned_end_date",
                    models.DateField(help_text="Planned end date for this work"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Monthly report this work belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upcoming_works",
                        to="reports.monthlyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upcoming Work",
                "verbose_name_plural": "Upcoming Works",
                "ordering": ["report", "planned_start_date"],
                "indexes": [
                    models.Index(
                        fields=["report"], name="reports_upc_report__589966_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly")],
                        help_text="Type of report",
                        max_length=10,
                    ),
                ),
                ("report_id", models.IntegerField(help_text="ID of the report")),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        default="photo",
                        help_text="Type of attachment",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached file",
                        upload_to="report_attachments/%Y/%m/%d/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the attachment",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Attachment",
                "verbose_name_plural": "Report Attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "report_id"],
                        name="reports_rep_report__a3efb9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyWorkForce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("management", "Management"),
                            ("skilled", "Skilled Labor"),
                            ("unskilled", "Unskilled Labor"),
                            ("contractor", "Contractor"),
                        ],
                        help_text="Category of workforce",
                        max_length=20,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Job designation or title", max_length=255
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        help_text="Number of workers in this category",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Monthly report this workforce belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workforce",
                        to="reports.monthlyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Work Force",
                "verbose_name_plural": "Monthly Work Forces",
                "ordering": ["report", "category"],
                "indexes": [
                    models.Index(
                        fields=["report", "category"],
                        name="reports_mon_report__35867f_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(
                fields=["project", "reporting_period_to"],
                name="reports_mon_project_4b4217_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(
                fields=["site_engineer", "reporting_period_to"],
                name="reports_mon_site_en_e711be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialsupply",
            index=models.Index(
                fields=["report"], name="reports_mat_report__d1d9c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flooractivity",
            index=models.Index(
                fields=["report", "floor"], name="reports_flo_report__123fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalwork",
            index=models.Index(
                fields=["report"], name="reports_ext_report__edb16e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyworkforce",
            index=models.Index(
                fields=["report", "category"], name="reports_dai_report__bc8b25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyvisitor",
            index=models.Index(
                fields=["report"], name="reports_dai_report__4af94b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyreport",
            index=models.Index(
                fields=["project", "report_date"], name="reports_dai_project_6704c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyreport",
            index=models.Index(
                fields=["site_engineer", "report_date"],
                name="reports_dai_site_en_3c5b83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailymaterial",
            index=models.Index(
                fields=["report"], name="reports_dai_report__c77aba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyequipment",
            index=models.Index(
                fields=["report"], name="reports_dai_report__90c85d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyactivity",
            index=models.Index(
                fields=["report", "activity_type"],
                name="reports_dai_report__3139e5_idx",
            ),
        ),
    ]
