# Generated by Django 5.2.4 on 2026-09-06 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_contract_value"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Equipment name (e.g., Fixed Winch, Dump Truck)",
                        max_length=150,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Equipment description and specifications"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Equipment manufacturer", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Equipment model", max_length=100
                    ),
                ),
                (
                    "year_built",
                    models.IntegerField(
                        blank=True,
                        help_text="Year equipment was built/manufactured",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Equipment category (e.g., Excavation, Concrete, Lifting)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this equipment is available for selection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipment Master",
                "verbose_name_plural": "Equipment Masters",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkforceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Project Management, Work Force)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this workforce category"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is available for selection",
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workforce Category",
                "verbose_name_plural": "Workforce Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="project",
            field=models.ForeignKey(
                help_text="Associated construction project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_reports",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="project",
            field=models.ForeignKey(
                help_text="Associated construction project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_reports",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="EmailReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the reminder configuration", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the reminder"
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report"),
                            ("monthly", "Monthly Report"),
                            ("both", "Both Daily and Monthly"),
                        ],
                        default="daily",
                        help_text="Type of report to remind about",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Every Day"),
                            ("weekly", "Every Week"),
                            ("bi_weekly", "Every Two Weeks"),
                            ("monthly", "Every Month"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        help_text="How often to send reminders",
                        max_length=20,
                    ),
                ),
                (
                    "send_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (8:00 AM)"),
                            ("afternoon", "Afternoon (1:00 PM)"),
                            ("evening", "Evening (5:00 PM)"),
                            ("end_of_day", "End of Day (6:00 PM)"),
                            ("custom", "Custom Time"),
                        ],
                        default="evening",
                        help_text="What time to send reminders",
                        max_length=20,
                    ),
                ),
                (
                    "custom_time",
                    models.TimeField(
                        blank=True,
                        help_text="Custom time to send reminders (if Custom Time selected)",
                        null=True,
                    ),
                ),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable or disable this reminder"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_engineers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Engineers to send reminders to (leave empty for all)",
                        related_name="email_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Projects to send reminders for (leave empty for all)",
                        related_name="email_reminders",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Reminder",
                "verbose_name_plural": "Email Reminders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text='Display code/number for this phase (e.g. "1", "2")',
                        max_length=20,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(help_text="Phase name in Arabic", max_length=255),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, help_text="Phase name in English", max_length=255
                    ),
                ),
                (
                    "weight_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="This phase's weight as a percentage of the TOTAL contract value",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the project"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Phase",
                "verbose_name_plural": "Project Phases",
                "ordering": ["project", "order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhaseSubItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        help_text="Sub-item name in Arabic", max_length=255
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, help_text="Sub-item name in English", max_length=255
                    ),
                ),
                (
                    "weight_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="This sub-item's weight as a percentage of the TOTAL contract value",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_completion_date", models.DateField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phase",
                    models.ForeignKey(
                        help_text="Parent phase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_items",
                        to="reports.projectphase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Phase Sub-item",
                "verbose_name_plural": "Project Phase Sub-items",
                "ordering": ["phase", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhaseProgressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(help_text="Date this progress reading applies to"),
                ),
                (
                    "execution_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cumulative % complete of this sub-item as of report_date",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Daily report this reading was captured in, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase_progress_entries",
                        to="reports.dailyreport",
                    ),
                ),
                (
                    "monthly_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monthly report this reading was captured in, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phase_progress_entries",
                        to="reports.monthlyreport",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_phase_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_item",
                    models.ForeignKey(
                        help_text="The sub-item this reading applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="reports.projectphasesubitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phase Progress Entry",
                "verbose_name_plural": "Phase Progress Entries",
                "ordering": ["sub_item", "-report_date"],
            },
        ),
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sent",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time reminder was sent to this engineer",
                        null=True,
                    ),
                ),
                (
                    "next_send",
                    models.DateTimeField(
                        help_text="Next scheduled time to send reminder"
                    ),
                ),
                (
                    "send_count",
                    models.IntegerField(
                        default=0, help_text="Number of times reminder has been sent"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this schedule is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.emailreminder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Schedule",
                "verbose_name_plural": "Reminder Schedules",
                "ordering": ["next_send"],
            },
        ),
        migrations.CreateModel(
            name="ReminderTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report Reminder"),
                            ("monthly", "Monthly Report Reminder"),
                            ("overdue", "Overdue Report Reminder"),
                            ("welcome", "Welcome Email"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=200),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML email body (use {{variables}} for placeholders)"
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True, help_text="Plain text email body (optional)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reminder Template",
                "verbose_name_plural": "Reminder Templates",
                "unique_together": {("template_type", "is_active")},
            },
        ),
        migrations.CreateModel(
            name="ReportMaterialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(help_text="Item code/reference", max_length=50),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Material/item description", max_length=255
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (e.g., kg, liters, pieces, m3)",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total quantity in BOQ",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unit rate/price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total amount (quantity × unit_rate)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Material category (e.g., Concrete, Steel, Bricks)",
                        max_length=100,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, help_text="Supplier name", max_length=150
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this BOQ item is available"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this material"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_material_items",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Material Item",
                "verbose_name_plural": "Report Material Items",
                "ordering": ["project", "category", "item_code"],
            },
        ),
        migrations.CreateModel(
            name="DailyReportMaterialEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of material used today",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_wasted",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of material wasted",
                        max_digits=12,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Remarks about material usage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Associated daily report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_entries",
                        to="reports.dailyreport",
                    ),
                ),
                (
                    "boq_item",
                    models.ForeignKey(
                        help_text="Material from project BOQ",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.reportmaterialitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Report Material Entry",
                "verbose_name_plural": "Daily Report Material Entries",
                "ordering": ["report", "boq_item__category", "boq_item"],
            },
        ),
        migrations.CreateModel(
            name="SiteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("delay", "Delay"),
                            ("site_instruction", "Site Instruction (SI)"),
                            ("rfi", "RFI"),
                            ("ncr", "NCR"),
                            ("hse_incident", "HSE Incident"),
                            ("near_miss", "Near Miss"),
                            ("other", "Other"),
                        ],
                        help_text="Type of event",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference number, e.g. NCR-014, RFI-022",
                        max_length=50,
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Date the event occurred / was raised",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the issue / instruction / delay"
                    ),
                ),
                (
                    "required_action",
                    models.TextField(
                        blank=True, help_text="Action required to resolve this event"
                    ),
                ),
                (
                    "responsible_party",
                    models.CharField(
                        blank=True,
                        help_text="External party responsible, if not an internal user (consultant, subcontractor, etc.)",
                        max_length=150,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="Target date for closing this event",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "time_impact_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Schedule time impact in hours, if any",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_site_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "daily_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Daily report this event was first logged in, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_events",
                        to="reports.dailyreport",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_events",
                        to="projects.project",
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal user responsible for closing this out",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_site_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Event",
                "verbose_name_plural": "Site Events",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Labor classification name (e.g., Project Manager, Civil Engineer)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this labor classification"
                    ),
                ),
                (
                    "default_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        help_text="Default gender for this classification",
                        max_length=1,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this classification is available",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Parent workforce category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_classifications",
                        to="reports.workforcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labor Classification",
                "verbose_name_plural": "Labor Classifications",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if email failed to send"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_id",
                    models.CharField(
                        blank=True,
                        help_text="Email service provider ID",
                        max_length=100,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="reports.emailreminder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-sent_at"],
                        name="reports_ema_recipie_30917a_idx",
                    ),
                    models.Index(
                        fields=["status", "-sent_at"],
                        name="reports_ema_status_5e5b20_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyReportEquipmentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_in_use",
                    models.IntegerField(
                        default=0, help_text="Quantity of this equipment in use"
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours this equipment worked",
                        max_digits=8,
                    ),
                ),
                (
                    "quantity_idle",
                    models.IntegerField(
                        default=0, help_text="Quantity of this equipment idle"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Remarks about equipment status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Associated daily report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_entries",
                        to="reports.dailyreport",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="Equipment from master list",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.equipmentmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Report Equipment Entry",
                "verbose_name_plural": "Daily Report Equipment Entries",
                "ordering": ["report", "equipment__category", "equipment"],
                "unique_together": {("report", "equipment")},
            },
        ),
        migrations.CreateModel(
            name="DailyReportWorkforceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_employees",
                    models.IntegerField(
                        default=0,
                        help_text="Number of employees in this classification",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        help_text="Gender of employees",
                        max_length=1,
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours worked by this group",
                        max_digits=8,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this workforce entry",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Associated daily report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workforce_entries",
                        to="reports.dailyreport",
                    ),
                ),
                (
                    "labor_classification",
                    models.ForeignKey(
                        help_text="Labor classification from master list",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.laborclassification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Report Workforce Entry",
                "verbose_name_plural": "Daily Report Workforce Entries",
                "ordering": [
                    "report",
                    "labor_classification__category",
                    "labor_classification",
                ],
                "unique_together": {("report", "labor_classification")},
            },
        ),
        migrations.AddIndex(
            model_name="projectphase",
            index=models.Index(
                fields=["project", "order"], name="reports_pro_project_87e5a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectphase",
            unique_together={("project", "code")},
        ),
        migrations.AddIndex(
            model_name="projectphasesubitem",
            index=models.Index(
                fields=["phase", "order"], name="reports_pro_phase_i_c5646f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectphaseprogressentry",
            index=models.Index(
                fields=["sub_item", "report_date"],
                name="reports_pro_sub_ite_b7bdd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminderschedule",
            index=models.Index(
                fields=["next_send", "is_active"], name="reports_rem_next_se_a20db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminderschedule",
            index=models.Index(
                fields=["engineer", "is_active"], name="reports_rem_enginee_1f435e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reminderschedule",
            unique_together={("reminder", "engineer")},
        ),
        migrations.AlterUniqueTogether(
            name="reportmaterialitem",
            unique_together={("project", "item_code")},
        ),
        migrations.AlterUniqueTogether(
            name="dailyreportmaterialentry",
            unique_together={("report", "boq_item")},
        ),
        migrations.AddIndex(
            model_name="siteevent",
            index=models.Index(
                fields=["project", "event_type"], name="reports_sit_project_8ef8f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteevent",
            index=models.Index(
                fields=["project", "status"], name="reports_sit_project_ebfd7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteevent",
            index=models.Index(
                fields=["event_date"], name="reports_sit_event_d_8e4b3b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="laborclassification",
            unique_together={("category", "name")},
        ),
    ]
