# Generated by Django 5.2.17 on 2026-09-06 11:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_equipmentmaster_workforcecategory_and_more'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportattachment',
            name='location',
            field=models.CharField(blank=True, help_text='Location on site where this attachment was captured', max_length=255),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='site_event',
            field=models.ForeignKey(blank=True, help_text='Site event (delay/NCR/HSE/...) this attachment documents, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='reports.siteevent'),
        ),
        migrations.CreateModel(
            name='DailyReportActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Location on site', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional detail beyond the BOQ item name')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (m3, m2, ton, ...)', max_length=50)),
                ('quantity_today', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity executed today', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_cumulative', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative quantity executed to date', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative % complete of this sub-item, as of this report', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(help_text='Daily report this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress_entries', to='reports.dailyreport')),
                ('sub_item', models.ForeignKey(help_text='BOQ sub-item this activity contributes to', on_delete=django.db.models.deletion.PROTECT, related_name='daily_activity_entries', to='reports.projectphasesubitem')),
            ],
            options={
                'verbose_name': 'Daily Report Activity Progress',
                'verbose_name_plural': 'Daily Report Activity Progress Entries',
                'ordering': ['report', 'sub_item'],
            },
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Daily activity this attachment documents, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='reports.dailyreportactivityprogress'),
        ),
        migrations.CreateModel(
            name='DailyReportNextDayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of planned work')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('responsible_party', models.CharField(blank=True, help_text='Crew / subcontractor responsible for this work', max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the table')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(help_text='Daily report this plan row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='next_day_plan', to='reports.dailyreport')),
                ('sub_item', models.ForeignKey(blank=True, help_text='BOQ sub-item this planned work maps to, if known', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_day_plan_entries', to='reports.projectphasesubitem')),
            ],
            options={
                'verbose_name': 'Daily Report Next-Day Plan Item',
                'verbose_name_plural': 'Daily Report Next-Day Plan Items',
                'ordering': ['report', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportQAQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending'), ('not_applicable', 'Not Applicable')], default='not_applicable', help_text="Result of today's QA/QC inspection, if any", max_length=20)),
                ('toolbox_talk_conducted', models.BooleanField(default=False)),
                ('toolbox_talk_topic', models.CharField(blank=True, max_length=255)),
                ('incident_occurred', models.BooleanField(default=False, help_text='An HSE incident occurred today')),
                ('near_miss_occurred', models.BooleanField(default=False, help_text='A near-miss occurred today')),
                ('ppe_compliant', models.BooleanField(default=True, help_text='Site-wide PPE compliance observed')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_site_event', models.ForeignKey(blank=True, help_text='NCR / HSE event this section refers to, if logged in the site events log', limit_choices_to={'event_type__in': ['ncr', 'hse_incident', 'near_miss']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qaqc_references', to='reports.siteevent')),
                ('report', models.OneToOneField(help_text='Daily report this QA/QC & HSE section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='qaqc', to='reports.dailyreport')),
            ],
            options={
                'verbose_name': 'Daily Report QA/QC & HSE',
                'verbose_name_plural': 'Daily Report QA/QC & HSE Sections',
            },
        ),
        migrations.CreateModel(
            name='DailyReportWorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(help_text='Worker full name, as written on site', max_length=255)),
                ('time_in', models.TimeField(blank=True, help_text='Check-in time', null=True)),
                ('time_out', models.TimeField(blank=True, help_text='Check-out time', null=True)),
                ('break_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Unpaid break time, in hours', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Overtime hours, added on top of time_in/time_out', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Computed: (time_out - time_in) - break_hours + overtime_hours', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Linked HR employee record, if this worker has one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_attendance', to='timesheets.employee')),
                ('labor_classification', models.ForeignKey(blank=True, help_text='Labor classification, for category-level rollups', null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.laborclassification')),
                ('report', models.ForeignKey(help_text='Daily report this attendance entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='worker_attendance', to='reports.dailyreport')),
            ],
            options={
                'verbose_name': 'Daily Report Worker Attendance',
                'verbose_name_plural': 'Daily Report Worker Attendance',
                'ordering': ['report', 'worker_name'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyreportactivityprogress',
            index=models.Index(fields=['report'], name='reports_dai_report__1a40df_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportactivityprogress',
            index=models.Index(fields=['sub_item'], name='reports_dai_sub_ite_cf4a48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreportactivityprogress',
            unique_together={('report', 'sub_item')},
        ),
        migrations.AddIndex(
            model_name='dailyreportnextdayplan',
            index=models.Index(fields=['report'], name='reports_dai_report__29cd15_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportworkerattendance',
            index=models.Index(fields=['report'], name='reports_dai_report__133bcf_idx'),
        ),
    ]
