# Generated by Django 5.2.17 on 2026-09-06 11:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportattachment_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreportactivityprogress',
            options={'ordering': ['report', 'id'], 'verbose_name': 'Daily Report Activity Progress', 'verbose_name_plural': 'Daily Report Activity Progress Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='dailyreportactivityprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailyreportnextdayplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dailyreportnextdayplan',
            name='planned_quantity',
        ),
        migrations.RemoveField(
            model_name='dailyreportnextdayplan',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='dailyreportqaqc',
            name='ppe_compliant',
        ),
        migrations.AddField(
            model_name='dailyreportactivityprogress',
            name='activity_description',
            field=models.TextField(default='', help_text='Description of the work/activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyreportactivityprogress',
            name='reference_notes',
            field=models.CharField(blank=True, help_text='Work reference / remarks (e.g. responsible crew, drawing ref.)', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyreportactivityprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('on_hold', 'On Hold')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyreportactivityprogress',
            name='total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total scope quantity for this activity', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='dailyreportnextdayplan',
            name='manpower_required',
            field=models.PositiveIntegerField(blank=True, help_text='Number of workers needed', null=True),
        ),
        migrations.AddField(
            model_name='dailyreportnextdayplan',
            name='planned_activity',
            field=models.TextField(default='', help_text='Description of the planned activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyreportnextdayplan',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='dailyreportnextdayplan',
            name='readiness',
            field=models.CharField(blank=True, choices=[('ready', 'Ready'), ('pending', 'Pending'), ('not_ready', 'Not Ready')], max_length=10),
        ),
        migrations.AddField(
            model_name='dailyreportnextdayplan',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyreportnextdayplan',
            name='requirement_notes',
            field=models.CharField(blank=True, help_text='Requirement or approval needed before this work can proceed', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyreportnextdayplan',
            name='resources_required',
            field=models.TextField(blank=True, help_text='Materials / equipment required'),
        ),
        migrations.AddField(
            model_name='dailyreportqaqc',
            name='ir_mir_test_reference',
            field=models.CharField(blank=True, help_text='Inspection Request / Material Inspection Request / Test reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreportqaqc',
            name='ncr_hse_reference',
            field=models.CharField(blank=True, help_text='Raw NCR / HSE reference text, if not yet logged as a formal site event', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreportqaqc',
            name='ppe_site_cleanliness_status',
            field=models.CharField(blank=True, help_text='Free-text PPE compliance / site cleanliness status (e.g. "OK", "Sound")', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreportworkerattendance',
            name='activity_location',
            field=models.CharField(blank=True, help_text='What/where this worker worked on today', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyreportworkerattendance',
            name='contractor_name',
            field=models.CharField(blank=True, help_text='Subcontractor/company this worker belongs to (e.g. "One Stop", a named subcontractor)', max_length=150),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Display order within the report's photo log (Photo 01, 02, ...)"),
        ),
        migrations.AlterField(
            model_name='dailyreportactivityprogress',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative % complete of this activity, as of this report', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='dailyreportactivityprogress',
            name='location',
            field=models.CharField(blank=True, help_text='Location / floor / area on site', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyreportactivityprogress',
            name='sub_item',
            field=models.ForeignKey(blank=True, help_text='BOQ sub-item this activity contributes to, if it maps to one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_activity_entries', to='reports.projectphasesubitem'),
        ),
        migrations.AlterField(
            model_name='dailyreportnextdayplan',
            name='sub_item',
            field=models.ForeignKey(blank=True, help_text='BOQ sub-item this planned work maps to, if known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_day_plan_entries', to='reports.projectphasesubitem'),
        ),
        migrations.RemoveField(
            model_name='dailyreportactivityprogress',
            name='description',
        ),
    ]
