# Generated by Django 5.2.17 on 2026-09-06 12:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_advance_payment_value_and_more'),
        ('reports', '0004_alter_dailyreportactivityprogress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsupply',
            name='delivered_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity delivered this period (EDGE "Materials Status" table)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='materialsupply',
            name='remaining_notes',
            field=models.CharField(blank=True, help_text='Remaining stock / notes (e.g. "Datasheet attached")', max_length=255),
        ),
        migrations.AddField(
            model_name='materialsupply',
            name='used_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity used this period', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OwnerFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(help_text='Auto-generated unique report number', max_length=50, unique=True)),
                ('report_date', models.DateField(auto_now_add=True, help_text='Date when report was created')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', help_text='Current status of the report', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, help_text='When the report was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('reporting_period_from', models.DateField(help_text='Start date of the reporting period')),
                ('reporting_period_to', models.DateField(help_text='End date of the reporting period (the "as of" date for progress)')),
                ('contract_value_snapshot', models.DecimalField(decimal_places=2, max_digits=15)),
                ('advance_payment_value_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('performance_retention_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('previous_payments_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative amount already certified/paid before this report (entered manually, matching the source report)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('progress_summary', models.TextField(blank=True, help_text='"ملخص سير المشروع" narrative')),
                ('next_month_expected_works', models.TextField(blank=True, help_text='"الأعمال المتوقعة للشهر القادم"')),
                ('next_month_expected_completion_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Expected cumulative completion % by next month', max_digits=5, null=True)),
                ('material_price_note', models.TextField(blank=True, help_text='"الوضع الراهن لأسعار المواد" narrative')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Project manager who approved the report', limit_choices_to={'role': 'project_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Associated construction project', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='projects.project')),
                ('site_engineer', models.ForeignKey(help_text='Site engineer who created the report', limit_choices_to={'role': 'site_engineer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Financial Report',
                'verbose_name_plural': 'Owner Financial Reports',
                'ordering': ['-reporting_period_to', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerReportPriceComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('concrete_grade', 'Concrete Grade'), ('equipment', 'Equipment'), ('material', 'Other Material')], max_length=20)),
                ('item_name', models.CharField(help_text='e.g. "B450", "Bobcat", "مواد وطمم"', max_length=150)),
                ('unit', models.CharField(help_text='e.g. كوب / ساعة / يوم / طلعة', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity executed this month', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('old_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_difference', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Computed: (new_unit_price - old_unit_price) * quantity', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Owner financial report this price comparison belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='price_comparison_items', to='reports.ownerfinancialreport')),
            ],
            options={
                'verbose_name': 'Owner Report Price Comparison Item',
                'verbose_name_plural': 'Owner Report Price Comparison Items',
                'ordering': ['report', 'item_type', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='phase_photos/%Y/%m/')),
                ('caption', models.TextField(blank=True, help_text='Description / location / activity / reference')),
                ('taken_date', models.DateField(default=django.utils.timezone.localdate)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_photos', to='reports.dailyreport')),
                ('monthly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_photos', to='reports.monthlyreport')),
                ('owner_financial_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_photos', to='reports.ownerfinancialreport')),
                ('phase', models.ForeignKey(help_text='Project phase this photo documents', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.projectphase')),
                ('sub_item', models.ForeignKey(blank=True, help_text='Specific sub-item this photo documents, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='reports.projectphasesubitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Phase Photo',
                'verbose_name_plural': 'Project Phase Photos',
                'ordering': ['phase', 'order', '-taken_date'],
            },
        ),
        migrations.AddIndex(
            model_name='ownerfinancialreport',
            index=models.Index(fields=['project', 'reporting_period_to'], name='reports_own_project_1fcbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphasephoto',
            index=models.Index(fields=['phase', 'taken_date'], name='reports_pro_phase_i_8161e8_idx'),
        ),
    ]
