# Generated by Django 5.2.17 on 2026-09-07 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_materialsupply_delivered_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='site_engineer',
            field=models.ForeignKey(help_text='User who authored the report (site engineer for daily reports, project manager for monthly/owner financial reports)', limit_choices_to={'role__in': ['site_engineer', 'project_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='site_engineer',
            field=models.ForeignKey(help_text='User who authored the report (site engineer for daily reports, project manager for monthly/owner financial reports)', limit_choices_to={'role__in': ['site_engineer', 'project_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerfinancialreport',
            name='site_engineer',
            field=models.ForeignKey(help_text='User who authored the report (site engineer for daily reports, project manager for monthly/owner financial reports)', limit_choices_to={'role__in': ['site_engineer', 'project_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
