# Generated by Django 5.2.17 on 2026-09-07 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_dailyreport_site_engineer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason given when the engineering manager or general manager rejected this report'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='When the engineering manager reviewed the report', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Engineering manager who reviewed the report (first approval stage)', limit_choices_to={'role': 'engineering_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason given when the engineering manager or general manager rejected this report'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='When the engineering manager reviewed the report', null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Engineering manager who reviewed the report (first approval stage)', limit_choices_to={'role': 'engineering_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason given when the engineering manager or general manager rejected this report'),
        ),
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='When the engineering manager reviewed the report', null=True),
        ),
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Engineering manager who reviewed the report (first approval stage)', limit_choices_to={'role': 'engineering_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='When the report received final approval', null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='General manager who gave final approval', limit_choices_to={'role': 'general_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('engineering_approved', 'Approved by Engineering Manager'), ('approved', 'Approved by General Manager'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', help_text='Current status of the report', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='When the report received final approval', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='General manager who gave final approval', limit_choices_to={'role': 'general_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('engineering_approved', 'Approved by Engineering Manager'), ('approved', 'Approved by General Manager'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', help_text='Current status of the report', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownerfinancialreport',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='When the report received final approval', null=True),
        ),
        migrations.AlterField(
            model_name='ownerfinancialreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='General manager who gave final approval', limit_choices_to={'role': 'general_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerfinancialreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('engineering_approved', 'Approved by Engineering Manager'), ('approved', 'Approved by General Manager'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', help_text='Current status of the report', max_length=20),
        ),
    ]
