# Generated by Django 5.2.17 on 2026-09-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dailyreport_rejection_reason_dailyreport_review_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='closing_note',
            # null=True and NO default= at all here (unlike the original hand-authored version of this
            # migration) -- MySQL/MariaDB reject any literal DEFAULT on a TEXT/BLOB column outright
            # (error 1067). null=True alone wasn't enough to stop Django from still emitting one against
            # this server's Django 5.2.4 (it did work locally against 5.2.17 -- a real behavior
            # difference between those two patch releases' MySQL schema editor); dropping `default`
            # from the operation's field entirely is unambiguous on any version, since Django only
            # emits a DEFAULT clause when the field passed to AddField has one. The model's own
            # Python-level default (reports/owner_financial_models.py) still pre-fills this for every
            # new report going forward -- unaffected, since that's applied by the ORM/forms, not by a
            # database column default.
            field=models.TextField(blank=True, null=True, help_text='Closing "ملاحظة تنظيمية متعلقة بالتدفق المالي للمشروع" note (pre-filled with the standard wording, editable per report)'),
            # Tells the migration autodetector this field's real (model-level) default is intentionally
            # not represented here, so `makemigrations` doesn't propose an AlterField to "restore" it --
            # which would hit the exact same MySQL error 1067 the moment it tried to ADD that default.
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OwnerReportPhaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', '✅ Completed'), ('in_progress', '🔄 In Progress'), ('pending', '⏳ Not Started')], default='in_progress', max_length=20)),
                ('work_performed', models.TextField(help_text='"الأعمال المنفذة" -- free-text description of work done this period')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(help_text='Project phase this status line describes', on_delete=django.db.models.deletion.CASCADE, related_name='owner_report_updates', to='reports.projectphase')),
                ('report', models.ForeignKey(help_text='Owner financial report this phase status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='phase_updates', to='reports.ownerfinancialreport')),
            ],
            options={
                'verbose_name': 'Owner Report Phase Update',
                'verbose_name_plural': 'Owner Report Phase Updates',
                'ordering': ['report', 'order', 'phase__order'],
            },
        ),
    ]
