# Generated by Django 5.2.17 on 2026-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_ownerfinancialreport_closing_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerreportphaseupdate',
            name='status',
            field=models.CharField(choices=[('done', 'منجزة'), ('in_progress', 'قيد التنفيذ'), ('pending', 'لم تبدأ بعد')], default='in_progress', max_length=20),
        ),
    ]
