# Generated by Django 5.2.17 on 2026-09-10 07:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_ownerreportphaseupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='executive_summary',
            field=models.TextField(blank=True, help_text='"Executive Summary" narrative -- project status, phase transition, cumulative progress.'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='hse_corrective_actions_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Corrective Actions Open / Closed'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='hse_lti_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lost Time Incidents (LTI)'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='hse_near_misses_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Near Misses Reported (NM)'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='hse_site_inspections_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site Inspections Conducted'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='hse_toolbox_talks_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Toolbox Talks Conducted (TBT)'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='next_month_plan',
            field=models.TextField(blank=True, help_text='Plan for next month, one activity per line'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='qc_inspections_note',
            field=models.TextField(blank=True, help_text='Inspections / tests conducted this month'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='qc_nonconformances_note',
            field=models.TextField(blank=True, help_text='Non-conformances raised and status'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='qc_pending_submittals_note',
            field=models.TextField(blank=True, help_text='Approvals / material submittals pending'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='schedule_variance_note',
            field=models.CharField(blank=True, help_text='e.g. "≈ +3 days (ahead of schedule), based on 900 calendar days"', max_length=255),
        ),
        migrations.AlterField(
            model_name='ownerreportpricecomparisonitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative quantity used to date for this material/equipment line. "Copy for Next Period" carries this total forward; use "Add Quantity" on the report to add just the new period\'s usage on top of it.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='MonthlyIssueRiskDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Issue / risk / delay description')),
                ('impact', models.TextField(blank=True, help_text='Impact on schedule, cost, or quality')),
                ('mitigation', models.TextField(blank=True, help_text='Mitigation / action taken or planned')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Monthly report this issue/risk/delay belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='issues_risks_delays', to='reports.monthlyreport')),
            ],
            options={
                'verbose_name': 'Monthly Issue / Risk / Delay',
                'verbose_name_plural': 'Monthly Issues / Risks / Delays',
                'ordering': ['report', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyKeyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(help_text='Activity / work item, e.g. "Columns & walls of the ground floor"')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started'), ('delayed', 'Delayed')], default='in_progress', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Monthly report this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='key_activities', to='reports.monthlyreport')),
            ],
            options={
                'verbose_name': 'Monthly Key Activity',
                'verbose_name_plural': 'Monthly Key Activities',
                'ordering': ['report', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProgressCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g. "Civil / Structural Works"', max_length=150)),
                ('planned_value', models.CharField(blank=True, help_text='e.g. "≈ 32.6%" or "—"', max_length=150)),
                ('actual_value', models.CharField(blank=True, help_text='e.g. "In progress (Phase 3)" or "Not started (0%)"', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Monthly report this progress row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='progress_category_items', to='reports.monthlyreport')),
            ],
            options={
                'verbose_name': 'Monthly Progress Category Item',
                'verbose_name_plural': 'Monthly Progress Category Items',
                'ordering': ['report', 'order', 'id'],
            },
        ),
    ]
