# Generated by Django 5.2.17 on 2026-09-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_monthlyreport_executive_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='revision_note',
            field=models.CharField(blank=True, help_text='Brief note on what changed in this revision, e.g. "Addressed EDGE comments on slab photos"', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='revision_number',
            field=models.PositiveIntegerField(default=1, help_text='Revision number of this report for its reporting period (Rev01, Rev02, ... after supervision comments)'),
        ),
        migrations.CreateModel(
            name='MonthlyReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Short topic/reference for the comment, e.g. "Photo-01" or "Insulation Thickness"', max_length=150)),
                ('comment_text', models.TextField(help_text="The supervision/consultant's comment")),
                ('response_text', models.TextField(blank=True, help_text="The contractor's response to the comment")),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Monthly report this supervision comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='reports.monthlyreport')),
            ],
            options={
                'verbose_name': 'Monthly Review Comment',
                'verbose_name_plural': 'Monthly Review Comments',
                'ordering': ['report', 'order', 'id'],
            },
        ),
    ]
