# Generated by Django 5.2.17 on 2026-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_monthlyreport_revision_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='photos_external_link',
            field=models.URLField(blank=True, help_text='Link to the full external photo album (e.g. Dropbox folder) for this reporting period', max_length=500),
        ),
    ]
