# Generated by Django 5.2.17 on 2026-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_monthlyreport_photos_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='section_order',
            field=models.CharField(blank=True, help_text='Comma-separated section ids controlling display order on the report page; blank = default order', max_length=500),
        ),
    ]
