# Generated by Django 5.2.17 on 2026-09-12 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_monthlyreport_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsupply',
            name='material_type',
            field=models.CharField(blank=True, choices=[('concrete_grade', 'Concrete Grade'), ('equipment', 'Equipment'), ('material', 'Other Material')], help_text='Broad category, e.g. Concrete Grade / Equipment / Other Material', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialsupply',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Cumulative quantity used to date for this material. Set once on creation; use the "Add Quantity" action to add just the new period\'s usage on top of it.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
