# Generated by Django 5.2.17 on 2026-09-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_materialsupply_material_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsupply',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit, for the preliminary cost estimate. Real supplier quotes should replace any placeholder value entered here.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='materialsupply',
            name='unit_price_is_estimated',
            field=models.BooleanField(default=False, help_text='True if unit_price is a random placeholder (no real quote yet), not an actual price'),
        ),
    ]
