# Generated by Django 5.2.17 on 2026-09-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_materialsupply_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(help_text='Milestone name in Arabic', max_length=255)),
                ('name_en', models.CharField(blank=True, help_text='Milestone name in English', max_length=255)),
                ('baseline_date', models.DateField(help_text='Originally planned/contracted date')),
                ('forecast_date', models.DateField(blank=True, help_text='Current expected date, if revised from the baseline', null=True)),
                ('actual_date', models.DateField(blank=True, help_text='Date the milestone was actually achieved', null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(help_text='BOQ phase this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='reports.projectphase')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['phase', 'order', 'baseline_date'],
                'indexes': [models.Index(fields=['phase', 'baseline_date'], name='reports_pro_phase_i_84f60f_idx')],
            },
        ),
    ]
