# Generated by Django 5.2.17 on 2026-09-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_site_engineer_alter_project_manager'),
        ('reports', '0016_projectmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_task_id', models.PositiveIntegerField(help_text="The task's ID (row position) in the source .mpp file")),
                ('unique_id', models.PositiveIntegerField(help_text="The task's UniqueID in the source .mpp file (stable across reordering)")),
                ('name', models.CharField(max_length=500)),
                ('outline_level', models.PositiveSmallIntegerField(default=1, help_text='WBS indentation level')),
                ('is_summary', models.BooleanField(default=False, help_text='True for a summary/parent task (rolled up from children)')),
                ('is_milestone', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.DecimalField(blank=True, decimal_places=2, help_text='Working-day duration, as computed by the scheduling software', max_digits=7, null=True)),
                ('duration_text', models.CharField(blank=True, help_text='e.g. "34 days" -- as displayed by the source software', max_length=50)),
                ('percent_complete', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_slack_days', models.DecimalField(blank=True, decimal_places=2, help_text='Total float, in working days, as computed by the scheduling software', max_digits=7, null=True)),
                ('is_critical', models.BooleanField(default=False, help_text="True if the scheduling software flagged this task as being on the project's critical path")),
                ('predecessors', models.CharField(blank=True, help_text='Raw predecessor list, as shown by the source software (e.g. "10,15FS+14 days")', max_length=255)),
                ('resource_names', models.CharField(blank=True, max_length=255)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this schedule task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Schedule Task',
                'verbose_name_plural': 'Schedule Tasks',
                'ordering': ['project', 'source_task_id'],
                'indexes': [models.Index(fields=['project', 'is_critical'], name='reports_sch_project_0cfd44_idx')],
                'unique_together': {('project', 'source_task_id')},
            },
        ),
    ]
