# Generated by Django 5.2.17 on 2026-09-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_scheduletask'),
        ('timesheets', '0008_dailyworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportworkerattendance',
            name='daily_worker',
            field=models.ForeignKey(blank=True, help_text="Link to the shared day-labor roster, so this worker's hours across every project they worked this month can be aggregated for payroll", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_entries', to='timesheets.dailyworker'),
        ),
    ]
