# Generated by Django 5.2.17 on 2026-09-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_dailyreportworkerattendance_daily_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='budget_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected cost per unit', max_digits=14),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='contract_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit under the contract (what the owner pays)', max_digits=14),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='section',
            field=models.CharField(blank=True, help_text='Bill-of-quantities section this item belongs to, e.g. "Civil Works" -- used to group and subtotal', max_length=100),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measure, e.g. m2, m, No., L.S.', max_length=20),
        ),
        migrations.AddField(
            model_name='projectphasesubitem',
            name='budget_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected cost per unit', max_digits=14),
        ),
        migrations.AddField(
            model_name='projectphasesubitem',
            name='code',
            field=models.CharField(blank=True, help_text='Item number in the bill of quantities, e.g. 1.17.1', max_length=20),
        ),
        migrations.AddField(
            model_name='projectphasesubitem',
            name='contract_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit under the contract (what the owner pays)', max_digits=14),
        ),
        migrations.AddField(
            model_name='projectphasesubitem',
            name='is_whole',
            field=models.BooleanField(default=False, editable=False, help_text='The automatic stand-in for a phase that is priced as a whole (see ProjectPhase.sync_whole_item)'),
        ),
        migrations.AddField(
            model_name='projectphasesubitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphasesubitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measure, e.g. m2, m, No., L.S.', max_length=20),
        ),
    ]
