# Generated by Django 5.2.17 on 2026-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_boq_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='activity_id',
            field=models.CharField(blank=True, help_text='Activity ID as shown in the schedule, e.g. A1010', max_length=30),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='actual_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='actual_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='baseline_finish',
            field=models.DateField(blank=True, help_text='Finish in the approved baseline schedule', null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='baseline_start',
            field=models.DateField(blank=True, help_text='Start in the approved baseline schedule', null=True),
        ),
    ]
