# Generated by Django 5.2.17 on 2026-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_scheduletask_activity_id_scheduletask_actual_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='work_hours_note',
            field=models.TextField(blank=True, help_text='Site engineer\'s note on how today\'s man-hours split between staff and labor, e.g. "24 hrs staff / 8 hrs workers"', null=True),
        ),
    ]
