# Generated by Django 5.2.17 on 2026-09-27 06:00

from django.db import migrations, models


def mark_project_management_as_staff(apps, schema_editor):
    """The company's existing "Project Management" workforce category (Project Manager, Civil Engineer,
    Safety Manager, Office Engineer, ...) is what "staff" (موظفين) means here, as opposed to "Work Force" /
    "عمالة عامة" (عمال) -- set on the data that already exists so the Daily Report's man-hours split works
    immediately, without anyone having to open the Admin panel first."""
    WorkforceCategory = apps.get_model('reports', 'WorkforceCategory')
    WorkforceCategory.objects.filter(name='Project Management').update(is_staff_category=True)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_dailyreport_work_hours_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcecategory',
            name='is_staff_category',
            field=models.BooleanField(default=False, help_text='Counts as "staff" (موظفين) rather than "workers" (عمال) when the Daily Report splits man-hours between the two on its KPI strip -- e.g. Project Management vs Work Force'),
        ),
        migrations.RunPython(mark_project_management_as_staff, migrations.RunPython.noop),
    ]
