# Generated by Django 5.2.17 on 2026-09-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_workforcecategory_is_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyequipment',
            name='activity',
            field=models.ForeignKey(blank=True, help_text="Which of this report's logged activities this equipment was used for", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_used', to='reports.dailyreportactivityprogress'),
        ),
        migrations.AddField(
            model_name='dailyequipment',
            name='equipment_master',
            field=models.ForeignKey(blank=True, help_text='Chosen from the equipment list; required going forward, nullable only so historical rows recorded before this list existed still load', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_usage', to='reports.equipmentmaster'),
        ),
        migrations.AlterField(
            model_name='dailyequipment',
            name='equipment_name',
            field=models.CharField(blank=True, help_text='Set automatically from the chosen equipment; kept editable only for historical rows from before the equipment list existed', max_length=255),
        ),
    ]
