# Generated by Django 5.2.17 on 2026-09-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_dailyequipment_activity_and_more'),
        ('subcontractors', '0003_subcontractoragreement_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportworkerattendance',
            name='contractor_name',
            field=models.CharField(blank=True, help_text='Subcontractor/company this worker belongs to (e.g. "One Stop", a named subcontractor); auto-filled from crew when this worker is part of one', max_length=150),
        ),
        migrations.CreateModel(
            name='DailyReportCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Masonry Crew A", "Crew 1"', max_length=100)),
                ('contractor_name', models.CharField(blank=True, help_text='Company this crew belongs to (e.g. "One Stop" for an in-house crew); auto-filled from the agreement above when one is set', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, help_text="Which of this report's logged activities this crew is executing", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crews', to='reports.dailyreportactivityprogress')),
                ('agreement', models.ForeignKey(blank=True, help_text='Subcontractor agreement this crew works under, if it is a subcontracted crew', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_crews', to='subcontractors.subcontractoragreement')),
                ('report', models.ForeignKey(help_text='Daily report this crew belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='reports.dailyreport')),
            ],
            options={
                'verbose_name': 'Daily Report Crew',
                'verbose_name_plural': 'Daily Report Crews',
                'ordering': ['report', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dailyreportworkerattendance',
            name='crew',
            field=models.ForeignKey(blank=True, help_text='Crew this worker is part of, on a project with more than one crew working the same day -- when set, contractor_name/activity_location are taken from the crew rather than entered per worker', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='reports.dailyreportcrew'),
        ),
    ]
