# Generated by Django 5.2.17 on 2026-09-28 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_alter_dailyreportworkerattendance_contractor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date this report covers (the work date being reported on) -- editable so a report written up the next morning still records the day it actually covers, not the day it was filed; see created_at for the real filing timestamp'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date this report covers (the work date being reported on) -- editable so a report written up the next morning still records the day it actually covers, not the day it was filed; see created_at for the real filing timestamp'),
        ),
        migrations.AlterField(
            model_name='ownerfinancialreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date this report covers (the work date being reported on) -- editable so a report written up the next morning still records the day it actually covers, not the day it was filed; see created_at for the real filing timestamp'),
        ),
    ]
