# Generated by Django 5.2.17 on 2026-09-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_alter_dailyreport_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='reminder',
            field=models.ForeignKey(blank=True, help_text='The scheduled reminder config this email came from, if any -- an ad-hoc check (e.g. check_overdue_daily_reports) logs its emails with this left unset', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='reports.emailreminder'),
        ),
    ]
