# Generated by Django 5.2.17 on 2026-10-06 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_applicable_spec_sections'),
        ('reports', '0026_alter_emaillog_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportworkerattendance',
            name='sub_name',
            field=models.CharField(blank=True, help_text='متفرقة -- which sub-group (odd job) of the project this day-labor entry belongs to; blank = the project itself', max_length=120),
        ),
        migrations.CreateModel(
            name='ProjectSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive subs are no longer offered to the site engineer')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project sub (متفرقة)',
                'verbose_name_plural': 'Project subs (متفرقات)',
                'ordering': ['project', 'order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
