# Generated by Django 5.2.17 on 2026-10-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_project_sub_and_attendance_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseScheduleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_unique_id', models.PositiveIntegerField(help_text="MS Project Unique ID of a (leaf) plan task that carries this phase's work")),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_links', to='reports.projectphase')),
            ],
            options={
                'verbose_name': 'Phase / plan task link',
                'verbose_name_plural': 'Phase / plan task links',
                'ordering': ['phase', 'task_unique_id'],
                'unique_together': {('phase', 'task_unique_id')},
            },
        ),
    ]
