# Generated by Django 5.2.17 on 2026-10-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_phase_schedule_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='idle_reason',
            field=models.CharField(blank=True, choices=[('weekly_rest', 'Weekly rest day (Friday)'), ('public_holiday', 'Public holiday'), ('weather', 'Bad weather'), ('closure', 'Closure / security situation'), ('owner_stop', 'Stopped by the owner or the consultant'), ('waiting', 'Waiting for materials or approvals'), ('other', 'Other (explain in the remarks)')], help_text='Why no work was done (only for an idle day)', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='site_status',
            field=models.CharField(choices=[('working', 'Working day'), ('idle', 'Idle day - no work on site')], default='working', help_text='Whether work was done on site that day', max_length=10),
        ),
    ]
