# Generated by Django 5.2.17 on 2026-10-10 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_dailyreport_site_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When a manager / engineer deleted this draft; the admin approves or restores it', null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text="Who deleted this draft (pending the admin's approval)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When a manager / engineer deleted this draft; the admin approves or restores it', null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text="Who deleted this draft (pending the admin's approval)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When a manager / engineer deleted this draft; the admin approves or restores it', null=True),
        ),
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text="Who deleted this draft (pending the admin's approval)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
    ]
