# Generated by Django 5.2.17 on 2026-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_report_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='frozen_at',
            field=models.DateTimeField(blank=True, help_text='When the report was frozen as final (its figures no longer follow the live progress)', null=True),
        ),
        migrations.AddField(
            model_name='ownerfinancialreport',
            name='frozen_progress',
            field=models.JSONField(blank=True, help_text='The progress breakdown as it was when the report was frozen', null=True),
        ),
    ]
