# Generated by Django 5.2.17 on 2026-09-21 07:19

import ai_assistant.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
        ('projects', '0006_backfill_project_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('boq_extract', 'Read a document into a draft BOQ'), ('project_review', 'Project review')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('running', 'Working'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('source_file', models.FileField(blank=True, help_text='A file uploaded straight to the assistant', upload_to=ai_assistant.models.ai_upload_path)),
                ('instructions', models.TextField(blank=True, help_text="Anything the reader should know, e.g. 'the quantities are in section 3 only'")),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('import_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='projects.project')),
                ('source_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blueprints.blueprintrevision')),
                ('source_tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projecttenderdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
