# Generated by Django 5.2.17 on 2026-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airun',
            name='kind',
            field=models.CharField(choices=[('boq_extract', 'Read a document into a draft BOQ'), ('drawing_takeoff', 'Materials, quantities and green-building data'), ('project_review', 'Project review')], max_length=20),
        ),
    ]
