# Generated by Django 5.2.17 on 2026-09-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_site_engineer_alter_project_manager'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlocation',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this check-in/out is attributed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_checkins', to='projects.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this employee is currently assigned to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employees', to='projects.project'),
        ),
        migrations.AddField(
            model_name='geofence',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project site this geofence covers, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofences', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='checkinlocation',
            index=models.Index(fields=['project', '-timestamp'], name='timesheets__project_e7579d_idx'),
        ),
    ]
