# Generated by Django 5.2.17 on 2026-09-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_leaverequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_working_hours', models.PositiveIntegerField(default=160, help_text='Standard hours/month a salary is divided by to get the hourly rate')),
                ('daily_working_hours', models.PositiveIntegerField(default=8, help_text='Hours per day before extra hours count as overtime')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('is_default', models.BooleanField(default=False, help_text='Used for any employee with no salary structure of their own')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_structure',
            field=models.ForeignKey(blank=True, help_text='Pay policy (overtime/weekend rules) for this employee; falls back to the default structure if unset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='timesheets.salarystructure'),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('weekend_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekend_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holiday_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Not computed automatically yet -- enter manually until deduction rules are defined', max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='timesheets.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_generated', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='timesheets.salarystructure')),
            ],
            options={
                'ordering': ['-period_start', 'employee'],
                'unique_together': {('employee', 'period_start', 'period_end')},
            },
        ),
    ]
