# Generated by Django 5.2.17 on 2026-09-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_salarystructure_employee_salary_structure_payslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Unpaid break subtracted from a day's check-in/out span before splitting it into regular/overtime hours", max_digits=4),
        ),
    ]
