# Generated by Django 5.2.17 on 2026-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_holiday_salarystructure_break_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='deductions',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='advances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سلف -- manual entry', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='بدلات أخرى -- manual entry (e.g. transport, car)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مقتطعات -- manual entry, distinct from advances', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pay_basis',
            field=models.CharField(choices=[('salaried', 'Salaried (fixed monthly)'), ('hourly', 'Hourly (from GPS attendance)')], default='salaried', max_length=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الضريبة -- shown for information only; NOT subtracted from net_pay (separate process)', max_digits=12),
        ),
    ]
