# Generated by Django 5.2.17 on 2026-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_remove_payslip_deductions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='monthly_working_hours',
            field=models.PositiveIntegerField(default=240, help_text='Standard hours/month a salary is divided by to get the hourly rate (30 days x daily_working_hours)'),
        ),
    ]
