# Generated by Django 5.2.17 on 2026-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_alter_salarystructure_monthly_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('trade', models.CharField(blank=True, help_text='e.g. "عامل طوبار", "فني ميكانيك"', max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Wage for one full 8-hour day', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
