# Generated by Django 5.2.17 on 2026-09-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0011_payslip_posted_at_payslip_posted_by_payslip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Auto-counted from DailyAttendanceRecord rows marked 'unpaid_leave' this period (leave taken beyond the employee's annual_leave_days balance)", max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='unpaid_leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='unpaid_leave_days x (salary / 30) -- auto-computed, subtracted from net pay', max_digits=12),
        ),
        migrations.CreateModel(
            name='DailyAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave (Paid)'), ('unpaid_leave', 'Unpaid Leave'), ('rest_day', 'Rest Day'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('undertime_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='timesheets.employee')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='timesheets__employe_4968e8_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
