# Generated by Django 5.2.17 on 2026-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0014_dailyworkerpayslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_days',
            field=models.PositiveIntegerField(default=14, help_text='No longer used to compute leave balance -- that is now tenure-based automatically (14 days/year under 5 years of service, 21 days/year at 5+), see services.attendance_service._annual_leave_allocation. Kept only for legacy records.'),
        ),
    ]
