# Generated by Django 5.2.17 on 2026-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0015_alter_employee_annual_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworker',
            name='id_document',
            field=models.FileField(blank=True, help_text='Scanned ID/identity document, captured once when this worker is first added to the roster', null=True, upload_to='daily_worker_ids/'),
        ),
    ]
