# Generated by Django 5.2.17 on 2026-09-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_alter_dailyreportworkerattendance_contractor_name_and_more'),
        ('timesheets', '0016_dailyworker_id_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='default_labor_classification',
            field=models.ForeignKey(blank=True, help_text='Daily Report trade to pre-select when an employee with this position is picked for worker attendance (e.g. Site Engineer -> Project Management/Site Engineer), so their own presence can be logged without re-typing a trade that their position already implies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.laborclassification'),
        ),
    ]
