# Generated by Django 5.2.17 on 2026-10-03 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_applicable_spec_sections'),
        ('timesheets', '0018_seed_position_default_labor_classification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkerManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First day of the month this entry belongs to')),
                ('days', models.DecimalField(decimal_places=2, default=0, help_text='Total full 8-hour days in the month', max_digits=6)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='اليومية -- wage for one full 8-hour day', max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_worker_manual_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_wage_entries', to='projects.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='timesheets.dailyworker')),
            ],
            options={
                'verbose_name_plural': 'Daily worker manual entries',
                'ordering': ['worker__full_name'],
                'unique_together': {('worker', 'project', 'period_start')},
            },
        ),
    ]
