# Generated by Django 5.2.17 on 2026-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0019_dailyworkermanualentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkermanualentry',
            name='advances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سلف -- advance deducted on this line', max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyworkerpayslip',
            name='line_advances',
            field=models.DecimalField(decimal_places=2, default=0, help_text="سلف typed on the worker's per-project lines of the Manual Entry tab (not edited here)", max_digits=12),
        ),
    ]
