# Generated by Django 5.2.17 on 2026-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_applicable_spec_sections'),
        ('timesheets', '0020_manual_entry_advances_line_advances'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyworkermanualentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyworkermanualentry',
            name='sub_name',
            field=models.CharField(blank=True, help_text='متفرقات -- an optional named sub-group inside the project (e.g. one odd job of a "miscellaneous" project); blank = the project itself', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='dailyworkermanualentry',
            unique_together={('worker', 'project', 'period_start', 'sub_name')},
        ),
    ]
