# Generated by Django 5.2.17 on 2026-10-06 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0021_manual_entry_sub_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkerpayslip',
            name='accounting_approved_at',
            field=models.DateTimeField(blank=True, help_text='Set when the accountant approves; the payment voucher of the worker can be printed from then on', null=True),
        ),
        migrations.AddField(
            model_name='dailyworkerpayslip',
            name='accounting_approved_by',
            field=models.ForeignKey(blank=True, help_text='The accountant who approved this month for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wage_slips', to=settings.AUTH_USER_MODEL),
        ),
    ]
