# Generated by Django 5.2.17 on 2026-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0022_wage_slip_accounting_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='manual_base_pay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typed by HR in the payroll run instead of the salary-based base pay (blank = automatic)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='manual_unpaid_leave_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typed by HR instead of the automatic unpaid-leave deduction (blank = automatic)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='note',
            field=models.CharField(blank=True, help_text='Free note on this employee for this month', max_length=300),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('excluded', 'Excluded')], default='draft', max_length=10),
        ),
    ]
