# Generated by Django 5.2.17 on 2026-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0023_payslip_manual_figures_and_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payroll_order',
            field=models.PositiveIntegerField(default=0, help_text='Position of the employee in the payroll sheet and its exports (1 = first), set with the up/down arrows on the Payroll Run page; 0 = not placed yet (listed after the placed ones, alphabetically)'),
        ),
    ]
