# Generated by Django 5.2.17 on 2026-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0025_payroll_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='manual_actual_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Attendance days typed by HR instead of the days counted from GPS clock-ins (blank = automatic). Display only: does not change pay', max_digits=5, null=True),
        ),
    ]
