# Generated by Django 5.2.17 on 2026-10-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0027_employee_project_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Lunch / rest break inside the day (hours), taken off the time between clock in and clock out', max_digits=4),
        ),
    ]
