# Generated by Django 5.2.17 on 2026-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_applicable_spec_sections'),
        ('timesheets', '0028_dailyattendance_break_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprojecthours',
            options={'ordering': ['date', 'project__name', 'sub_name']},
        ),
        migrations.AlterUniqueTogether(
            name='employeeprojecthours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeprojecthours',
            name='sub_name',
            field=models.CharField(blank=True, help_text='متفرقة -- which sub-group (odd job) of the project these hours went to; blank = the project itself', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='employeeprojecthours',
            unique_together={('employee', 'date', 'project', 'sub_name')},
        ),
    ]
