# Generated by Django 5.2.17 on 2026-09-20 09:18

import blueprints.models
import django.db.models.deletion
import projects.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_projectinsurance_projecttenderdocument_projectstage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('discipline', models.CharField(choices=[('architectural', 'Architectural'), ('structural', 'Structural'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('civil', 'Civil / site'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='projects.project')),
            ],
            options={
                'ordering': ['discipline', 'drawing_number'],
                'unique_together': {('project', 'drawing_number')},
            },
        ),
        migrations.CreateModel(
            name='BlueprintRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(help_text='e.g. 0, A, B, R1', max_length=20)),
                ('file', models.FileField(upload_to=blueprints.models._revision_upload_path, validators=[projects.validators.validate_document_file])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved for construction'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blueprints.blueprint')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('blueprint', 'revision')},
            },
        ),
    ]
