# Generated by Django 4.2.27 on 2026-01-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='short_code',
            field=models.CharField(db_index=True, editable=False, max_length=20),
        ),
    ]
