# Generated by Django 5.2.17 on 2026-09-15 11:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_itemmaster_short_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('m', 'Meter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('pcs', 'Pieces'), ('set', 'Set'), ('lot', 'Lot'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('bag', 'Bag'), ('box', 'Box'), ('roll', 'Roll'), ('sheet', 'Sheet'), ('liter', 'Liter')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
            ],
            options={
                'ordering': ['po', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('m', 'Meter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('pcs', 'Pieces'), ('set', 'Set'), ('lot', 'Lot'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('bag', 'Bag'), ('box', 'Box'), ('roll', 'Roll'), ('sheet', 'Sheet'), ('liter', 'Liter')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['pr', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RFQVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False, help_text='Winning quote chosen by the Procurement Officer')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='polineitem',
            name='po',
        ),
        migrations.RemoveField(
            model_name='polineitem',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='boq_item',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='quantity_requested',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='quantity_required',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand/manufacturer, if known', max_length=200),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='source_code',
            field=models.CharField(blank=True, db_index=True, help_text='Original 11-digit code from the source item-classification spreadsheet, if imported from it', max_length=20),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='variant_suffix',
            field=models.PositiveSmallIntegerField(default=0, help_text='Disambiguates source rows that legitimately share one classification code but are different items (0 = no conflict)'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Procurement officer tracking this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='rejected_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Site engineer who created this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='unit',
            field=models.CharField(blank=True, choices=[('m', 'Meter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('pcs', 'Pieces'), ('set', 'Set'), ('lot', 'Lot'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('bag', 'Bag'), ('box', 'Box'), ('roll', 'Roll'), ('sheet', 'Sheet'), ('liter', 'Liter')], help_text='Typical unit of measure, for reference only -- the actual unit is chosen per purchase-requisition line', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchaserequisition'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Project manager who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='required_date',
            field=models.DateField(help_text='Date the materials are needed by'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_procurement', 'In Procurement'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['source_code'], name='procurement_source__01634f_idx'),
        ),
        migrations.AddField(
            model_name='poreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='procurement.itemmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='poreceipt',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='procurement.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='boq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_lines', to='procurement.billofquantities'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pr_lines', to='procurement.itemmaster'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='pr_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='procurement.purchaserequisitionline'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='rfqvendor',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_vendors', to='procurement.requestforquotation'),
        ),
        migrations.AddField(
            model_name='rfqvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_invitations', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='vendorquote',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorquote',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='procurement.requestforquotation'),
        ),
        migrations.AddField(
            model_name='vendorquote',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_quote',
            field=models.ForeignKey(blank=True, help_text='The winning RFQ quote this PO was generated from, if any (blank for a direct/emergency purchase)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.vendorquote'),
        ),
        migrations.AddField(
            model_name='vendorquoteline',
            name='pr_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='procurement.purchaserequisitionline'),
        ),
        migrations.AddField(
            model_name='vendorquoteline',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.vendorquote'),
        ),
        migrations.DeleteModel(
            name='POLineItem',
        ),
        migrations.AddIndex(
            model_name='poreceipt',
            index=models.Index(fields=['po_line', 'received_date'], name='procurement_po_line_ab138e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfqvendor',
            unique_together={('rfq', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorquote',
            unique_together={('rfq', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorquoteline',
            unique_together={('quote', 'pr_line')},
        ),
    ]
