# Generated by Django 5.2.17 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_poreceipt_purchaseorderline_purchaserequisitionline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='barcode_value',
            field=models.CharField(blank=True, default='', editable=False, help_text="Scannable Code128 barcode number: a fixed internal-use prefix, then this item's own AA-BB-CC-DD-EEE classification code, its variant suffix, and a mod-10 check digit -- the item's own code IS the middle of the barcode, not a separate lookup number.", max_length=20),
        ),
    ]
