# Generated by Django 5.2.17 on 2026-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_itemmaster_barcode_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorquote',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='vendorquoteline',
            name='is_selected',
            field=models.BooleanField(default=False, help_text="This vendor's price was chosen for this specific item"),
        ),
    ]
