# Generated by Django 5.2.17 on 2026-09-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_remove_vendorquote_is_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFamily',
            fields=[
                ('code', models.CharField(help_text="aa_level, e.g. '03'", max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Item families',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="bb_category, e.g. '04'", max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='procurement.itemfamily')),
            ],
            options={
                'ordering': ['family__code', 'code'],
                'unique_together': {('family', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="cc_subcategory, e.g. '01'", max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='procurement.itemgroup')),
            ],
            options={
                'ordering': ['group__family__code', 'group__code', 'code'],
                'unique_together': {('group', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="dd_itemtype, e.g. '01'", max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_types', to='procurement.itemclassification')),
            ],
            options={
                'ordering': ['classification__group__family__code', 'classification__group__code', 'classification__code', 'code'],
                'unique_together': {('classification', 'code')},
            },
        ),
    ]
