# Generated by Django 5.2.17 on 2026-09-19 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_rename_itemtypegroup_to_itembrand'),
        ('projects', '0004_project_site_engineer_alter_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='barcode_value',
            field=models.CharField(blank=True, default='', editable=False, help_text="Scannable Code128 value: the item's own Family/Group/Classification/Brand/attribute codes, each letter-prefixed so the barcode's own text is self-describing on sight (e.g. 'F03G04C01B01T000'), plus a variant suffix if the item has one -- confirmed with the client as preferable to a plain numeric code with a check digit.", max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text="Leave blank for a general/main warehouse; set it for a project's own site store", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Received from supplier'), ('issue', 'Issued to project'), ('adjustment', 'Stock count / correction')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Signed: positive = in, negative = out', max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='procurement.itemmaster')),
                ('po_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='procurement.poreceipt')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='projects.project')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='procurement.warehouse')),
            ],
            options={
                'ordering': ['-created_date', '-id'],
                'indexes': [models.Index(fields=['warehouse', 'item', 'created_date'], name='procurement_warehou_281512_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock. The quantity on hand must not drop below this -- once it reaches it, the item must be re-ordered (0 = no limit)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, help_text='How much to order when the item runs low (0 = order enough to get back to twice the minimum)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='procurement.itemmaster')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='procurement.warehouse')),
            ],
            options={
                'ordering': ['item__full_code', 'warehouse__name'],
                'unique_together': {('warehouse', 'item')},
            },
        ),
    ]
