# Generated by Django 5.2.17 on 2026-09-20 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_warehouse_stock'),
        ('reports', '0018_dailyreportworkerattendance_daily_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofquantities',
            name='contract_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Contract total (sell)'),
        ),
        migrations.AddField(
            model_name='billofquantities',
            name='contract_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='What the owner pays per unit under the contract (0 = not priced)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Contract unit price (sell)'),
        ),
        migrations.AddField(
            model_name='billofquantities',
            name='phase',
            field=models.ForeignKey(blank=True, help_text="The work phase this item belongs to. Its measured progress is what this line's earned value is based on; leave blank to use the whole project's overall progress.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='reports.projectphase'),
        ),
        migrations.AlterField(
            model_name='billofquantities',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Budget total (cost)'),
        ),
        migrations.AlterField(
            model_name='billofquantities',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='What we expect to pay per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget unit price (cost)'),
        ),
    ]
