# Generated by Django 5.2.17 on 2026-09-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_control', '0002_remove_budget_boq_item_budgetalert_sub_item_and_more'),
        ('procurement', '0010_boq_contract_price_and_phase'),
        ('reports', '0019_boq_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisitionline',
            name='boq_item',
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='sub_item',
            field=models.ForeignKey(blank=True, help_text='The project BOQ item this purchase is charged to (copied from the requisition line when there is one)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='reports.projectphasesubitem'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='sub_item',
            field=models.ForeignKey(blank=True, help_text='The project BOQ item this material is bought for -- what cost control charges it to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_lines', to='reports.projectphasesubitem'),
        ),
        migrations.DeleteModel(
            name='BillOfQuantities',
        ),
    ]
